name: Deploy Convocation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          ssh-keyscan -H ${{ secrets.129.159.20.236 }} >> ~/.ssh/known_hosts

          ssh ${{ secrets.ubuntu }}@${{ secrets.129.159.20.236 }} << 'EOF'
            cd ${{ secrets./home/ubuntu/convocation-spa/BPHC-Convocation }}
            git pull origin main
            npm install
            pm2 restart all
          EOF